export const metaConfig: any = {
	dataview: "PL_MDVIEW_004",
	// serverUrl: "http://dev.veritech.mn:8080/erp-services/RestWS/runJson",
	serverUrl: "http://172.169.88.72:8080/erp-services/RestWS/runJson",
	fileAttach: "https://dev.veritech.mn:8181/erp-services/FileServlet",
	imageUrl: "https://dev.veritech.mn/",
	METATYPE_METAGROUP: "200101010000016",
	METATYPE_BUSINESSPROCESS: "200101010000011",
	COMMAND_DATAVIEW: "PL_MDVIEW_004",
	COMMAND_PAGECONFIG: "layoutHdr_004",
	metaDev: {
		serverUrl: "http://dev.veritech.mn:8080/erp-services/RestWS/runJson",
		fileAttach: "https://dev.veritech.mn:8181/erp-services/FileServlet",
		thisis: "Энэ бол DEV юм шүү.",
		username: "VR045", //VR045 mobileUser01
		password: "89",
		metaName: "metaDev",
		imageRootURL: "https://dev.veritech.mn/",

		// serverUrl: "http://erp.skyresort.mn:8080/erp-services/RestWS/runJson",
		// fileAttach: "http://erp.skyresort.mn:8080/erp-services/FileServlet",
		// thisis: "Энэ CloudNew юм шүү.",
		// username: "cadmin",
		// password: "Veritech@123",
		// metaName: "metaDev",
		// imageRootURL: "erp.skyresort.mn/",

		//cloud ****************
		// serverUrl: "http://172.169.88.72:8080/erp-services/RestWS/runJson",
		// fileAttach: "http://172.169.88.72:8080/erp-services/FileServlet",
		// thisis: "Энэ Cloud юм шүү.",
		// username: "admin",
		// password: "Verix123@",
		// metaName: "metaCloud",
		// imageRootURL: "https://cloud.veritech.mn/app/",
		//* end cloud *************
		//cloud ****************
		// serverUrl: "http://172.169.88.72:8383/erp-services/RestWS/runJson",
		// fileAttach: "http://172.169.88.72:8383/erp-services/FileServlet",
		// thisis: "Энэ CloudNew юм шүү.",
		// username: "admin",
		// password: "VRcloudAdmin@123",
		// metaName: "metaDev",
		// imageRootURL: "https://cloudnew.veritech.mn/app/",
		//* end cloud *************
	},
	metaCloud: {
		serverUrl: "http://172.169.88.72:8080/erp-services/RestWS/runJson",
		fileAttach: "http://172.169.88.72:8080/erp-services/FileServlet",
		thisis: "Энэ doc юм шүү.",
		username: "admin",
		password: "Verix123@",
		metaName: "metaCloud",
		imageRootURL: "https://cloud.veritech.mn/app/",
	},
	metaDevCloud: {
		serverUrl: "http://172.169.88.101:8080/erp-services/RestWS/runJson",
		fileAttach: "http://172.169.88.101:8080/erp-services/FileServlet",
		thisis: "Энэ бол DevCloud юм шүү.",
		username: "admin",
		password: "Verix123@",
		metaName: "metaDevCloud",
		imageRootURL: "https://devcloud.veritech.mn/app/",
	},
	metaSkyresort: {
		serverUrl: "http://dev.veritech.mn:8080/erp-services/RestWS/runJson",
		fileAttach: "http://dev.veritech.mn:8080/erp-services/FileServlet",
		thisis: "Энэ бол Sky Resort юм шүү.",
		username: "testuserskyresort",
		password: "123",
		// username: "ariunbuyan.t",
		// password: "123",
		metaName: "metaSkyresort",
		imageRootURL: "https://dev.veritech.mn/",
	},
	metaDoc: {
		serverUrl: "http://172.169.88.102:13015/erp-services/RestWS/runJson",
		fileAttach: "http://172.169.88.102:13015/erp-services/FileServlet",
		thisis: "Энэ doc юм шүү.",
		username: "admin",
		password: "Process@admin",
		metaName: "metaDoc",
		imageRootURL: "https://process.veritech.mn/",
	},
};
